name: hai_market
description: My own portfolio project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^1.5.3
  provider: ^6.0.2
  cupertino_icons: ^1.0.2
  freezed: ^2.3.2
  equatable: ^2.0.5
  retrofit: '>=3.0.0 <4.0.0'
  hive: any
  hive_flutter: any
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.1
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.20
  path_provider: ^2.0.11
  intl: ^0.18.0
  url_launcher: ^6.1.10
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  hive_generator: ^2.0.0
  injectable_generator: ^1.5.3
  flutter_lints: ^2.0.0
  retrofit_generator: '>=4.0.0 <5.0.0'
  json_serializable: '>4.4.0'


flutter:
  uses-material-design: true
  assets:
    - assets/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
